---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - pause:
        prompt: "Enter password"
        echo: no
      when: password is undefined
      register: password_input

    - set_fact:
        password: "{{ password_input.user_input }}"
      when: password is undefined

    - ec2_vpc_net_info:
        region: us-west-2
        filters:
          "tag:Name": ansible
      register: ansible_vpc

    - ec2_vpc_subnet_info:
        region: us-west-2
        filters: 
          vpc-id: "{{ ansible_vpc.vpcs[0].vpc_id }}"
      register: ansible_subnet

    - name: Ensure a security group is present
      ec2_group:
        name: linux-sg
        description: linux sg
        vpc_id: "{{ ansible_vpc.vpcs[0].vpc_id }}"
        region: us-west-2
        tags:
          Name: linux
          project: ansible-poc
          environment: dev
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
            rule_desc: Allow traffic on port 80 from anywhere
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
            rule_desc: Allow SSH traffic on port 22 from anywhere

    - name: Ensure EC2 key pair is present
      ec2_key: 
        name: aws-ansible-key
        region: us-west-2
        state: present
      register: ec2_key

    - name: Ensure private key is saved to disk
      copy: content="{{ ec2_key.key.private_key }}" dest="./aws-ansible-key.pem" mode=0600
      when: ec2_key.changed

    - name: Ensure Linux EC2 is present
      ec2:
        key_name: aws-ansible-key
        instance_type: t3.micro
        image: ami-001628438d5d7d524
        region: us-west-2
        group: linux-sg
        count: 1
        vpc_subnet_id: "{{ ansible_subnet.subnets[0].id }}"
        user_data: |
          #!/bin/bash
          sudo adduser ansible
          sudo echo "{{ password }}" | passwd --stdin ansible
          echo 'ansible        ALL=(ALL)       NOPASSWD: ALL' >> /etc/sudoers
          sudo sed -n 'H;${x;s/\PasswordAuthentication no/PasswordAuthentication yes/;p;}' /etc/ssh/sshd_config > tmp_sshd_config
          sudo cat tmp_sshd_config > /etc/ssh/sshd_config
          rm -f tmp_sshd_config
          sudo service sshd restart
        wait: yes
        assign_public_ip: yes
        instance_tags:
          Name: Lin-Web01
          project: ansible-poc
          environment: dev
          os: linux
      register: ec2

    - name: Ensure elastic IP association is present for each EC2 instance
      ec2_eip:
        device_id: "{{ item }}"
        release_on_disassociation: yes
        region: us-west-2
      loop: "{{ ec2.instance_ids }}"