---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - pause:
        prompt: "Enter password"
        echo: no
      when: password is undefined
      register: password_input

    - set_fact:
        password: "{{ password_input.user_input }}"
      when: password is undefined

    - ec2_vpc_net_info:
        region: us-west-2
        filters:
          "tag:Name": ansible
      register: ansible_vpc

    - ec2_vpc_subnet_info:
        region: us-west-2
        filters: 
          vpc-id: "{{ ansible_vpc.vpcs[0].vpc_id }}"
      register: ansible_subnet

    - name: Ensure a security group is present
      ec2_group:
        name: windows-sg
        description: windows sg
        vpc_id: "{{ ansible_vpc.vpcs[0].vpc_id }}"
        region: us-west-2
        tags:
          Name: windows
          project: ansible-poc
          environment: dev
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
            rule_desc: Allow traffic on port 80 from anywhere
          - proto: tcp
            from_port: 3389
            to_port: 3389
            cidr_ip: 0.0.0.0/0
            rule_desc: Allow RDP traffic on port 3389 from anywhere
          - proto: tcp
            from_port: 5985
            to_port: 5985
            cidr_ip: 0.0.0.0/0
            rule_desc: Allow WinRM over HTTP from anywhere
          - proto: tcp
            from_port: 5986
            to_port: 5986
            cidr_ip: 0.0.0.0/0
            rule_desc: Allow WinRM over HTTPS from anywhere

    - name: Ensure EC2 key pair is present
      ec2_key: 
        name: aws-ansible-key
        region: us-west-2
        state: present
      register: ec2_key

    - name: Ensure private key is saved to disk
      copy: content="{{ ec2_key.key.private_key }}" dest="./aws-ansible-key.pem" mode=0600
      when: ec2_key.changed

    - name: Ensure Windows EC2 is present
      ec2:
        key_name: aws-ansible-key
        instance_type: t3.micro
        image: ami-0b7ebdd52b84c244d
        region: us-west-2
        group: windows-sg
        count: 1
        vpc_subnet_id: "{{ ansible_subnet.subnets[0].id }}"
        user_data: |
          <powershell>
          $content = (Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1' -UseBasicParsing).content
          iex $content
          $password = "{{ password }}" | ConvertTo-SecureString -AsPlainText -Force
          New-LocalUser 'ansible' -Password $password
          Add-LocalGroupMember -Group 'Administrators' -Member 'ansible'
          </powershell>
          <persist>true</persist>
        wait: yes
        assign_public_ip: yes
        instance_tags:
          Name: Win-Web01
          project: ansible-poc
          environment: dev
          os: windows
      register: ec2

    - name: Ensure elastic IP association is present for each EC2 instance
      ec2_eip:
        device_id: "{{ item }}"
        release_on_disassociation: yes
        region: us-west-2
      loop: "{{ ec2.instance_ids }}"