---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - pause:
        prompt: "Enter password"
        echo: no
      when: password is undefined
      register: password_input

    - set_fact:
        password: "{{ password_input.user_input }}"
      when: password is undefined

    - ec2_vpc_net_info:
        region: us-west-2
        filters:
          "tag:Name": ansible
      register: ansible_vpc

    - ec2_vpc_subnet_info:
        region: us-west-2
        filters: 
          vpc-id: "{{ ansible_vpc.vpcs[0].vpc_id }}"
      register: ansible_subnet