---
- hosts: localhost
  gather_facts: false
  connection: local

  vars:
    ec2:ids: []
    sg_ids: []

  tasks:
    - name: Get VPC info
      ec2_vpc_net_info:
      region: us-west-2
      filters: 
        "tag:Name": ansible
      register: ansible_vpc

    - name: Get EC2 instance info
      ec2_instance_info:
      region: us-west-2
      filters: 
        "tag:project": ansible-poc
        "tag:environment": dev
        instance-state-name: [ "running"]
      register: ec2

    - set_fact:
        ec2_ids: "{{ ec2_ids }} + [ '{{ item.instance_id }}' ]"
      loop: "{{ ec2['instances'] }}"
      loop_control:
        label: "{{ item.instance_id }}"

    - name: Enure that elastic IP is diassociated from EC2 instance
      ec2_eip:
        region: us-west-2
        release_on_disassociation: yes
        device_id: "{{ item }}"
        state: absent
      with_items: "{{ ec2_ids }}" 
