---
- hosts: all
  gather_facts: false

  vars_prompt:
    - name: user
      prompt: "Enter local user name"
      private: no
    - name: password
      prompt: "Enter local user password"

  vars:
    ansible_user: "{{ user }}"
    ansible_password: "{{ password }}"
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore

  tasks:
  - name: run win_ping
    win_ping:
