# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    
    # General Vagrant VM configuration.
    config.vm.box = "geerlingguy/centos7"
    config.ssh.insert_key = false
    # The mount option prevents ansible warning 'Ansible is in a world writable directory'.
    # https://github.com/ansible/ansible/issues/42388
    config.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=775"]
    config.vm.provider :virtualbox do |v|
        v.memory = 512
        v.linked_clone = true
    end
  
    # Ansible controller.
    config.vm.define "controller" do |machine|
        machine.vm.hostname = "ansible.test"
        machine.vm.network :private_network, ip: "192.168.60.10"
        machine.vm.provision :ansible_local do |ansible|
            ansible.playbook       = "playbook.yml"
            ansible.verbose        = true
            ansible.install        = true
            ansible.limit          = "all" # or only "nodes" group, etc.
            ansible.inventory_path = "hosts.ini"
        end
    end

    # Application server 1.
    config.vm.define "app1" do |app|
        app.vm.hostname = "orc-app1.test"
        app.vm.network :private_network, ip: "192.168.60.4"
    end

    # Application server 2.
    config.vm.define "app2" do |app|
        app.vm.hostname = "orc-app2.test"
        app.vm.network :private_network, ip: "192.168.60.5"
    end

    # Database server.
    config.vm.define "db" do |db|
        db.vm.hostname = "orc-db.test"
        db.vm.network :private_network, ip: "192.168.60.6"
    end
end