---
- hosts: all
  gather_facts: false

  vars_prompt:
    - name: user
      prompt: "Enter SSH user"
      private: no
    - name: password
      prompt: "Enter SSH user password"

  vars:
    ansible_user: "{{ user }}"
    ansible_password: "{{ password }}"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
  - name: run ping
    ping: