---
- name: Register Windows TEMP environment variable
  win_shell: $env:TEMP
  register: temp_out
  changed_when: false

- name: Register Windows PROGRAMDATA environment variable
  win_shell: $env:PROGRAMDATA
  register: programData_out
  changed_when: false

- name: choco_location
  set_fact:
    choco_location: "{{ programData_out.stdout | trim + '\\chocolatey' }}"

- name: temp_location
  set_fact:
    temp_location: "{{ temp_out.stdout | trim  }}"

- name: Copy ChocolateyInstall.ps1
  win_copy:
    src: ChocolateyInstall.ps1
    dest: "{{ temp_location + '\\ChocolateyInstall.ps1' }}"

- name: Enure chocolatey is present
  win_chocolatey:
    name: chocolatey
    state: present
    source: "{{ temp_location + '\\ChocolateyInstall.ps1' }}"

- name: Copy chocolatey.extension
  win_copy: 
    src: chocolatey-core.extension.1.3.5.1.nupkg
    dest: "{{ temp_location + '\\chocolatey-core.extension.1.3.5.1.nupkg' }}"
  tags: chocolateyExtension

- name: Ensure chocolatey.extension is present
  win_chocolatey:
    name: chocolatey-core.extension
    state: present
    source: "{{ temp_location + '\\chocolatey-core.extension.1.3.5.1.nupkg' }}"
  tags: chocolateyExtension