---
name: Deploy Ansible
on: [push, pull_request]
#on: 
#  push: 
#    branches:
#    - master
#  pull_request:
#    branches:
#    - master


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1.0.0
    - uses: ./.github/actions/ansible