---
name: Deploy Ansible
on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Docker action
      uses: ./aws/  # Uses an action in the aws directory